version: '2'

services:
  kibana:
    network_mode: "host"
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
    - "5601:5601"

    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://localhost:9200

