# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Internal entry id')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('link', models.URLField(verbose_name='Link')),
                ('published_parsed', models.DateTimeField(verbose_name='Published')),
                ('entry_id', models.CharField(max_length=2083, verbose_name='Rss entry id')),
            ],
        ),
    ]
