# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:39
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20170217_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnotification',
            name='rating',
            field=models.SmallIntegerField(choices=[(0, 'default'), (1, 'upvoted'), (-1, 'downvoted')], default=0),
        ),
    ]
