# Generated by Django 2.2.2 on 2019-06-21 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20190620_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnotification',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
