# Generated by Django 2.2.2 on 2019-09-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedsource", "0004_auto_20190911_1932"),
        ("notification", "0005_rssnotification_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssnotification",
            name="feed_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rss_notifications",
                to="feedsource.FeedSource",
            ),
        ),
        migrations.AlterField(
            model_name="rssnotification",
            name="link",
            field=models.URLField(max_length=2083, verbose_name="Link"),
        ),
    ]
