# Generated by Django 2.2.2 on 2020-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_rssnotification_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssnotification',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
    ]
