# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:27
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('email_to', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.IntervalSchedule')),
            ],
        ),
    ]
