# Generated by Django 2.2.2 on 2019-06-21 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedsource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedsource',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
