# Generated by Django 2.2.2 on 2019-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedsource", "0002_auto_20190621_1451")]

    operations = [
        migrations.AddField(
            model_name="feedsource",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        )
    ]
