# Generated by Django 2.2.2 on 2019-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedsource", "0003_feedsource_name")]

    operations = [
        migrations.AlterField(
            model_name="feedsource",
            name="name",
            field=models.CharField(default="default-name", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedsource", name="url", field=models.URLField(max_length=2083)
        ),
    ]
