# Generated by Django 2.2.2 on 2019-09-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedsource', '0004_auto_20190911_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
